### ISSUE TITLE
Shutdown hook does not prevent failed state with SIGTERM

### ISSUE THREAD

**Issue by bmalinowsky** [Race666/calimero-server#13]
I recently added a shutdown hook to the server, but this obviously does not affect the Java exit code 143.

```
knx.service: Main process exited, code=exited, status=143/n/a
Stopped Calimero KNX Daemon.
knx.service: Unit entered failed state.
knx.service: Failed with result 'exit-code'.
```

Do you think it makes sense to handle it as success?

```
[Service]
SuccessExitStatus=143
````

**Comment by Race666** [comment]
Yes it makes :-). I would also an exit code 0 handle as succeded.

[Service]
SuccessExitStatus=0 143

Do you send me a pull request?
