### ISSUE TITLE
Server address and startup defaults in setup script

### ISSUE THREAD

**Issue by bmalinowsky** [Race666/calimero-server#9]
With routing enabled by default, please use a coupler address `x.y.0` for `KNX_ADDRESS`. (I also updated the server-config template to reflect that. Only a server _without_ routing might have a device address assigned for use in client connections).

On another note, I cherry-picked a CL option from master `--no-stdin` in https://github.com/calimero-project/calimero-server/commit/cf7089dc0feb711c310e9bc1f11453cd713bdd2a; when provided as first argument, it makes daemonizing the java process easier.

**Comment by Race666** [comment]
@bmalinowsky : Script is altered :+1:
